# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='TipoEstudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hcapp.TipoEstudio'),
        ),
    ]
