# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0003_auto_20170613_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerebroSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campo', models.TextField()),
                ('Conclusion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Fecha',
            new_name='Fecha_pedido',
        ),
        migrations.AddField(
            model_name='cerebrosimple',
            name='Estudio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.Estudio'),
        ),
    ]
