# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0004_auto_20170706_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
