# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0005_auto_20170614_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='CerebroSimple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.CerebroSimple'),
        ),
    ]
