# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0005_auto_20170708_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(blank=True, choices=[('AGFA', '8 X 10'), ('AGFA', '10 X 14'), ('AGFA', '14 X 17'), ('FUJI', '8 X 10'), ('FUJI', '10 X 14'), ('FUJI', '14 X 17')], max_length=255, null=True)),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
