# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0006_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='Cortecia',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
