# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0007_pedido_cortecia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='Edad',
        ),
    ]
