# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcapp', '0009_auto_20170729_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='Tipo',
            field=models.CharField(blank=True, choices=[('AGFA 8 X 10', 'AGFA 8 X 10'), ('AGFA 10 X 14', 'AGFA 10 X 14'), ('AGFA 14 X 17', 'AGFA 14 X 17'), ('FUJI 8 X 10', ' FUJI 8 X 10'), ('FUJI 10 X 14', 'FUJI 10 X 14'), ('FUJI 14 X 17', 'FUJI 14 X 17')], max_length=255, null=True),
        ),
    ]
