# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 22:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEstudio', models.CharField(max_length=200)),
                ('Fecha_creacion', models.DateField(auto_now=True)),
                ('Campo', models.TextField()),
                ('Conclusion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('Telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicoSolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('Telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.IntegerField(unique=True)),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('Telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Edad', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)])),
                ('Fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('Fecha_ingreso', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnostico_presuntivo', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha_pedido', models.DateField(auto_now=True)),
                ('Fecha', models.DateField(auto_now=True)),
                ('Historia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.Historia')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.MedicoSolicitante')),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoEstudio', models.CharField(max_length=200)),
                ('Fecha_creacion', models.DateField(auto_now=True)),
                ('Campo', models.TextField()),
                ('Conclusion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Radiologo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('Telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=128)),
                ('Apellido', models.CharField(max_length=128)),
                ('Telefono', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('Fecha_creacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha_creacion', models.DateField(auto_now=True)),
                ('Subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hcapp.Subcategoria')),
            ],
        ),
    ]
